version: '3.8'

services:
  php:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.31
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: safebase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./grant_privileges.sql:/docker-entrypoint-initdb.d/grant_privileges.sql
      # - ./safebase.sql:/docker-entrypoint-initdb.d/safebase.sql
      # - ./sql_dumps:/docker-entrypoint-initdb.d  # Directory for SQL dumps

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 20M
    ports:
      - "8081:80"
    depends_on:
      - mysql

  # Uncomment the following sections if you want to add PostgreSQL and pgAdmin
  # postgres:
  #   image: postgres:16
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: userpassword
  #     POSTGRES_DB: my_database
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./pg_dumps:/docker-entrypoint-initdb.d  # Directory for PostgreSQL dumps

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #   ports:
  #     - "8082:80"
  #   depends_on:
  #     - postgres

volumes:
  mysql_data:
  postgres_data:
